services:
  obsidian:
    image: 'ghcr.io/sytone/obsidian-remote:latest'
    restart: unless-stopped
    expose:
      - 8080
    volumes:
      - /home/obsidian/vaults:/vaults
      - /home/obsidian/config:/config
    environment:
      - SERVICE_FQDN_OBSIDIAN_8080
      - PUID=1000
      - PGID=1000
      - TZ=America/Santo_Domingo
      - DOCKER_MODS=linuxserver/mods:universal-git
      - CUSTOM_PORT="8080"
      - CUSTOM_USER="allan"
      - PASSWORD="${SERVICE_PASSWORD_PASSWORD}"
      - SUBFOLDER=""